{"author":{"id":"30705ab5e6f188236d1793cb07fc8a374ae274e0f48e0f8216153311596d1197"},"ops":[{"type":1,"author":{"id":"30705ab5e6f188236d1793cb07fc8a374ae274e0f48e0f8216153311596d1197"},"timestamp":1644963637,"metadata":{"github-id":"I_kwDOANZBd85D5-7F","github-url":"https://github.com/vmiklos/ged2dot/issues/201","origin":"github"},"nonce":"HFfvmI+WZ9A/StdxBRAxCVoH0Xo=","title":"Ubuntu / LibreOffice 7.3.0.3 / ElementTree.ParseError: no element found","message":"**Environment**\n- Ubuntu 20.04.3\n- LibreOffice 7.3.0.3\n\n**Reproducer steps**\n1. Open https://raw.githubusercontent.com/blokhin/genealogical-trees/master/data/tsars.ged with LibreOffice\n\n**Actual result**\n- Pop-up appears: `General input/output error.`\n- Console output:\n``` python\nfailed at node 1429[0]\ndot: maze.c:311: chkSgraph: Assertion `np-\u003ecells[0]' failed.\nTraceback (most recent call last):\n  File \"/home/john/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu429500spycr.tmp_/gedcom-7.3.oxt/importer.py\", line 125, in filter\n    buf = self.__to_svg(path)\n  File \"/home/john/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu429500spycr.tmp_/gedcom-7.3.oxt/importer.py\", line 103, in __to_svg\n    inlineize.inlineize(noinline, inline)\n  File \"/home/john/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu429500spycr.tmp_/gedcom-7.3.oxt/inlineize.py\", line 25, in inlineize\n    tree.parse(from_path)\n  File \"/usr/lib/python3.8/xml/etree/ElementTree.py\", line 595, in parse\n    self._root = parser._parse_whole(source)\nxml.etree.ElementTree.ParseError: no element found: line 1, column 0\n```\n\n**Expected behavior**\n- Some nice rendering.","files":null}]}